### ISSUE TITLE
how to add this functions into my existing react project with components.

### ISSUE THREAD

**Issue by DmitriyKushkulov** [paperbits/paperbits-demo#189]
I can't this function with the Components in existing my react project.

1. I have added the new router with '/paperbits' to add this component.
2. And then created the components that named Paperbits.
3. Also I didn't use the webpack.
4. this is the error screen for compile.

****Failed to compile.
./node_modules/@paperbits/common/persistence/offline.module.ts 11:27
Module parse failed: Unexpected token (11:27)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * Module registering components required for offline work.
|  */
> export class OfflineModule implements IInjectorModule {
|     constructor(private readonly options?: OfflineOptions) {
|         this.register = this.register.bind(this);****

5. Screenshots.
![image](https://user-images.githubusercontent.com/73977245/127331814-18e07b39-a13c-4173-ba2f-cdf678813d95.png)
![image](https://user-images.githubusercontent.com/73977245/127331938-eb0af995-4b7c-44b0-87cf-a482a051a4d5.png)
![image](https://user-images.githubusercontent.com/73977245/127332006-0d5668e0-423c-4164-b7b2-cdde0f561b30.png)
![image](https://user-images.githubusercontent.com/73977245/127332036-a70b2f50-a903-42d8-a322-5910db8dd861.png)

Please help me. really thanks.

**Comment by azaslonov** [comment]
Hi @DmitriyKushkulov, so this will not currently work without webpack, because it takes care of multiple things, i.e. loading referenced *.html files from npm packages. We are planning to publish packages with pre-compiled files along with Typings, so that scenario like yours would work, and we won't break existing customers, but this is coming later this year.

So, you either have to go with webpack, as shown in the demo project, or wait until we switch to new packaging.

**Comment by DmitriyKushkulov** [comment]
Hello. Alexander Zaslonov. 
really thanks.

**Comment by azaslonov** [comment]
I guess we forgot to close this issue, so doing it now.
