### ISSUE TITLE
Publish via button click

### ISSUE THREAD

**Issue by dandansoysauce** [paperbits/paperbits-demo#58]
Do we have something like building the static website through a button click? Or do I have to use sockets to call the publish command?

Awesome project and I would like to use this for project that I'm working on.

Thank you

**Comment by azaslonov** [comment]
Hi @dandansoysauce, thanks for the feedback. We don't include *Publish* button by default because we don't know how exactly publishing is going to happen in particular customer's setup. However, there is a good example in Microsoft's Azure API Management Developer Portal:
![image](https://user-images.githubusercontent.com/2320302/73478085-486d8780-434a-11ea-8943-c38c1ffbfd55.png)


You can find (and steal) the source (here)[https://github.com/Azure/api-management-developer-portal/tree/master/src/components/content]. It's under MIT license.

I'm closing the issue for now, but feel free to comment/re-open it shall you have other questions.

**Comment by AndersLindPedersen** [comment]
@azaslonov could you explain what happens on the backend part of the publish functionally in the API-Portal.

Wondering if a CI pipeline is triggers to run the npm publish process. Or the published portal is grapping the content dynamically from a remote storage, using a dynamic instead of static published portal?

**Comment by azaslonov** [comment]
Yes, this is exactly what happens, [it calls](https://github.com/Azure/API-Portal/blob/main/.github/workflows/publish-on-checkin.yml#L24) `npm run publish`. In the default setup, which is just a specific implementation of `IObjectStorage` (for data) and `IBlobStorage` (for media) interfaces, it takes the data from [content.json](https://github.com/Azure/API-Portal/blob/main/catalog/data/content.json) file.
