### ISSUE TITLE
Add VueJS startup example

### ISSUE THREAD

**Issue by dandansoysauce** [paperbits/paperbits-demo#61]
I know there's already an example for a vuejs component, but I'd like to know if there's a possibility of adding **vuejs** example for a startup.

Thank you.

**Comment by azaslonov** [comment]
Hi Dani, could you please clarify what do you mean by startup? Are we talking about files like startup.runtime.ts?

**Comment by dandansoysauce** [comment]
@azaslonov yes, that's correct. Right now, I am initiating the vue app under startup.design.ts by calling `new Vue({
    el: "#app"
});` after `injector.resolve("autostart");`

**Comment by azaslonov** [comment]
Looks like you're trying to do something with *design-time* experience, which might be pretty hard to run with Vue at the moment (still few things to be done on our side). The example that we have in this repo for Vue is a *run-rime* code (the code running on a published website), which is a much simpler case.

In order to help you better, it would be great to know what exactly you're trying to achieve/build. If you'd like we can discuss this offline, just shoot us an email to support@paperbits.io.

**Comment by dandansoysauce** [comment]
I've decided to go for KnockoutJS for easier implementation.
